function createfigure(X1, Y1, measure)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-May-2018 11:43:43

% Line width
line_width = 0.75;
marker_size = 10;

% Color
%line_color = [0 0.447058826684952 0.74117648601532];
line_color = [0 0 0];
gray_color = [0.501960813999176 0.501960813999176 0.501960813999176];


% Font weight
font_weight = 'normal'; % 'bold'

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',line_color,...
    'MarkerEdgeColor',line_color,...
    'Marker','.',...
    'MarkerSize',marker_size, ...
    'LineWidth',line_width,...
    'LineStyle','none');

% Interpolation
xx = X1(1):10:X1(end);
yy = spline(X1,Y1,xx);
mask = yy<0;
yy(mask) = 0;
plot(xx,yy,'Color',line_color,'LineStyle','-.','LineWidth',line_width)

% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight',font_weight,...
    'XColor',gray_color,'YColor',gray_color,'ZColor',gray_color, ...
    'XGrid','off', 'YGrid','on');

% Axes labels
xlabel('Cycles');
ylabel(measure);

% Window size
fig = gcf;
fig.PaperUnits = 'inches';
fig.PaperPosition = [0 0 6 3];
%print('5by3DimensionsFigure','-dpng','-r0')


